TM_AM_LOG_LEVEL ?= debug

IMAGE_NAME := amaas/amaas-grpc-ts-client-dev:latest

VERSION_LOCATION := './VERSION'
VERSION := $(shell cat $(VERSION_LOCATION))

# BSD sed does not support --version argument, use this to check if the sed is GNU or BSD one
ifeq ($(shell sed --version >/dev/null 2>&1; echo $$?),0)
SED := sed -i
else
SED := sed -i ''
endif

all: clean build

build:
	cp ./protos/scan.proto scan.proto
	$(SED) 's/__PACKAGE_VERSION__/$(VERSION)/' ./package.json
	docker build \
		-t $(IMAGE_NAME) \
		--build-arg TM_AM_LOG_LEVEL=$(TM_AM_LOG_LEVEL) \
		.
	$(SED) 's/$(VERSION)/__PACKAGE_VERSION__/' ./package.json
	mkdir -p output
	docker run --rm $(IMAGE_NAME) tar -cz cloudone-vsapi-$(VERSION).tgz | tar xzf - -C output

test:
	cp ./protos/scan.proto scan.proto
	docker build \
		--target unit_test \
		-t $(IMAGE_NAME) \
		--build-arg TM_AM_LOG_LEVEL=$(TM_AM_LOG_LEVEL) \
		.
	docker run --rm $(IMAGE_NAME) tar -cz coverage | tar xzf -

clean:
	-@docker rmi -f $(IMAGE_NAME) || true
	rm -f scan.proto
	rm -rf output
	rm -rf coverage

.PHONY: all build test clean
